sonar.projectKey=x0uill3_cesizen-monorepo
sonar.organization=x0uill3

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/*.test.ts,**/__tests__/**,**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=frontend/**,backend/src/utils/seeder.ts,backend/src/utils/changePassword.ts,backend/src/utils/generate*.mjs

sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/tsconfig.app.json
